# Generated by Django 4.2.16 on 2026-03-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="商品标题"
                    ),
                ),
                (
                    "shop",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="店铺名称"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="商品价格",
                    ),
                ),
                (
                    "pay_count",
                    models.IntegerField(blank=True, null=True, verbose_name="付款人数"),
                ),
                (
                    "ship_address",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="发货地址"
                    ),
                ),
                (
                    "detail_url",
                    models.TextField(blank=True, null=True, verbose_name="详情页地址"),
                ),
                (
                    "image_url",
                    models.TextField(blank=True, null=True, verbose_name="图片地址"),
                ),
                (
                    "features",
                    models.TextField(blank=True, null=True, verbose_name="特点列表"),
                ),
                (
                    "selling_points",
                    models.TextField(blank=True, null=True, verbose_name="卖点"),
                ),
                (
                    "product_brand",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="商品品牌"
                    ),
                ),
            ],
            options={
                "verbose_name": "淘宝商品数据",
                "verbose_name_plural": "淘宝商品数据",
                "db_table": "data",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="LoginStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="统计日期")),
                (
                    "login_count",
                    models.IntegerField(default=0, verbose_name="登录数量"),
                ),
            ],
            options={
                "verbose_name": "登录统计",
                "verbose_name_plural": "登录统计",
                "db_table": "login_statistics",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="用户名"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="密码")),
                (
                    "email",
                    models.CharField(max_length=50, unique=True, verbose_name="邮箱"),
                ),
                (
                    "user_text",
                    models.TextField(blank=True, null=True, verbose_name="个人简介"),
                ),
            ],
            options={
                "verbose_name": "用户信息",
                "verbose_name_plural": "用户信息",
                "db_table": "users",
            },
        ),
    ]
