"""
Django settings for djangoProject project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

from config import Config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-insecure-a=jk4h+jhkl4uvxhm5_(4m##7@%#8j=*sgc&s8tgx2njw-6ch$")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'simpleui',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'corsheaders',
    'app'
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "djangoProject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "djangoProject.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': Config.Database,    # 数据库名，如 'db_cp_tb_commodity_project'
        'USER': Config.User,        # 数据库用户名
        'PASSWORD': Config.Password, # 数据库密码
        'HOST': Config.Host,        # 数据库主机，如 'localhost'
        'PORT': Config.Port,        # 端口，默认 3306
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# 跨域配置
# 开发环境配置（允许所有源，便于调试）
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = ['*']
CORS_ALLOW_METHODS = ['DELETE', 'GET', 'OPTIONS', 'PATCH', 'POST', 'PUT']

# 生产/本地开发环境配置（推荐）
# 前端本地开发时的CSRF豁免域名
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]

CORS_ALLOW_CREDENTIALS = True

# 修复：导入 default_headers
from corsheaders.defaults import default_headers
CORS_ALLOW_HEADERS = list(default_headers) + [
    'content-type',
]

# ── SimpleUI 后台美化配置 ──────────────────────────────
SIMPLEUI_HOME_INFO = False          # 隐藏首页服务器信息
SIMPLEUI_ANALYSIS = False           # 不上报匿名数据
SIMPLEUI_DEFAULT_THEME = 'layui'    # 主题：layui / admin.lte / e-commerce 等
SIMPLEUI_LOGO = None                # 可替换为自定义 LOGO URL

SIMPLEUI_HOME_QUICK = True          # 显示快捷操作
SIMPLEUI_HOME_ACTION = True         # 显示最近动作

# 自定义菜单
SIMPLEUI_CONFIG = {
    'system_keep': False,           # 不保留系统默认菜单
    'menu_display': ['用户管理', '商品管理', '统计数据'],
    'dynamic': True,
    'menus': [
        {
            'name': '用户管理',
            'icon': 'fas fa-users',
            'models': [
                {
                    'name': '用户列表',
                    'icon': 'fas fa-user',
                    'url': 'app/user/',
                },
            ],
        },
        {
            'name': '商品管理',
            'icon': 'fas fa-shopping-cart',
            'models': [
                {
                    'name': '商品列表',
                    'icon': 'fas fa-box',
                    'url': 'app/data/',
                },
            ],
        },
        {
            'name': '统计数据',
            'icon': 'fas fa-chart-bar',
            'models': [
                {
                    'name': '登录统计',
                    'icon': 'fas fa-sign-in-alt',
                    'url': 'app/loginstatistics/',
                },
                {
                    'name': '系统用户',
                    'icon': 'fas fa-user-shield',
                    'url': 'auth/user/',
                },
            ],
        },
    ],
}
